services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dataDirectory: "%kimai.data_dir%"
            
    KimaiPlugin\WeeklyOverviewBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources/'

    KimaiPlugin\WeeklyOverviewBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    KimaiPlugin\WeeklyOverviewBundle\Command\WeeklyOverviewBackupCommand:
        tags: ['console.command']
