services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
            
    KimaiPlugin\WeeklyOverviewBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources/'

    KimaiPlugin\WeeklyOverviewBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
